baseURL = "https://dedsec-2.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Dedsec"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = true
  centerTheme = false
  autoCover = true
  showLastUpdated = false
  favicon = "/img/avatar.jpg"
  customCSS = ["css/custom.css"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[pagination]
  pagerSize = 5

[[params.social]]
  name = "github"
  url = "https://github.com/DEDSEC-2"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/d3d53c/"

[languages]
  [languages.en]
    languageName = "English"
    title = "Dedsec"
    weight = 1

    [languages.en.params]
      subtitle = "Offensive Security Notes"
      owner = "Momen Mahmoud"
      keywords = "cybersecurity, pentesting, redteam, offensive-security"
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"

      [languages.en.params.logo]
        logoText = "$ dedsec"
        logoHomeLink = "/"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts"
    [[languages.en.menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags"
